<?php //print_r($this->datos);?>
<form role="form" action="/usuario/edit" id="UsuarioEdit" method="post" >
<input type="hidden" name="user_id" name="user_id" value=<?php echo $this->datos['user_id']?>>
  <div class="form-group">
    <label>Nombre</label>
    <input type="text" class="form-control" id="nombre"  name="nombre" placeholder="<?php echo $this->datos['nombre']?>">
  </div>
  <div class="form-group">
    <label>Apellido Paterno</label>
    <input type="text" class="form-control" id="apellido_paterno" name="apellido_paterno" placeholder="<?php echo $this->datos['apellido_paterno']?>">
  </div>
  <div class="form-group">
    <label>Apellido Paterno</label>
    <input type="text" class="form-control" id="apellido_materno" name="apellido_materno" placeholder="<?php echo $this->datos['apellido_materno']?>">
  </div>
  
  
  <button type="submit" class="btn btn-default">Guardar</button>
</form>