<?php 
//print_r($this->all);

?>

<?php

$title = 'Usuario';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="/usuario/add">Add nuevo usuario</a>
</p>
<div class="panel panel-info">
<table class="table table-bordered">

        
<tr>

    <th class="danger">Nombre</th>
    <th class="danger">Primer Apellido</th>
    <th class="danger">Segundo Apellido</th>
    <th class="danger">Opciones&nbsp;</th>
    
</tr>

<?php foreach ($this->all as $usuario) : ?>
<tr>
    <td><?php echo $this->escapeHtml($usuario['nombre']);?></td>
    <td><?php echo $this->escapeHtml($usuario['apellido_materno']);?></td>
    <td><?php echo $this->escapeHtml($usuario['apellido_paterno']);?></td>
    <td>
    <a href="/usuario/edit/<?php echo $usuario['user_id'];?>">Editar</a>
    <a href="/usuario/delete/<?php echo $usuario['user_id'];?>">Borrar</a>
    
    </td>
</tr>

<?php endforeach; ?>
</table>
</div>
